package com.botExample.POJO;

public enum BotStates {
	TRAINS_SEARCH,
    TRAINS_SEARCH_STARTED,
    TRAINS_SEARCH_FINISH,
    ASK_SEARCH_LANGUAGE,
    ASK_STATION_DEPART,
    ASK_STATION_NUMBER,
    ASK_STATION_ARRIVAL,
    ASK_DATE_DEPART,
    ASK_TIME_DEPART,
    DATE_DEPART_RECEIVED,
    SHOW_MAIN_MENU,
    TRAIN_INFO_RESPONCE_AWAITING,
    SHOW_SUBSCRIPTIONS_MENU,
    SHOW_STATIONS_BOOK_MENU,
    STATIONS_SEARCH,
    SHOW_HELP_MENU;
}
